# Generated by Django 5.2.7 on 2026-01-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('duration_days', models.IntegerField()),
                ('duration_months', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('m_title', models.CharField(max_length=200)),
                ('no_of_sessions', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('topics', models.TextField()),
                ('session_number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.module')),
            ],
            options={
                'ordering': ['session_number'],
            },
        ),
    ]
