# Generated by Django 5.2.7 on 2026-01-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_course_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('trainer', 'Trainer'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
